# CMake generated Testfile for 
# Source directory: /home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit
# Build directory: /home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/test/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(proj_errno_string_test "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/proj_errno_string_test")
set_tests_properties(proj_errno_string_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests;PROJ_SOURCE_DATA=/home/denis/Documents/DIP7/Client/map/proj-9.2.0/data" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;90;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;0;")
add_test(proj_angular_io_test "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/proj_angular_io_test")
set_tests_properties(proj_angular_io_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests;PROJ_SOURCE_DATA=/home/denis/Documents/DIP7/Client/map/proj-9.2.0/data" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;100;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;0;")
add_test(proj_context_test "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/proj_context_test")
set_tests_properties(proj_context_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests;PROJ_SOURCE_DATA=/home/denis/Documents/DIP7/Client/map/proj-9.2.0/data" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;110;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;0;")
add_test(pj_phi2_test "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/pj_phi2_test")
set_tests_properties(pj_phi2_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests;PROJ_SOURCE_DATA=/home/denis/Documents/DIP7/Client/map/proj-9.2.0/data" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;123;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;0;")
add_test(proj_test_cpp_api "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/proj_test_cpp_api")
set_tests_properties(proj_test_cpp_api PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests;PROJ_SOURCE_DATA=/home/denis/Documents/DIP7/Client/map/proj-9.2.0/data" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;146;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;0;")
add_test(gie_self_tests "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/gie_self_tests")
set_tests_properties(gie_self_tests PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests;PROJ_SOURCE_DATA=/home/denis/Documents/DIP7/Client/map/proj-9.2.0/data" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;156;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;0;")
add_test(test_network "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/test_network")
set_tests_properties(test_network PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests;PROJ_SOURCE_DATA=/home/denis/Documents/DIP7/Client/map/proj-9.2.0/data" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;178;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;0;")
add_test(test_defmodel "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/test_defmodel")
set_tests_properties(test_defmodel PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests;PROJ_SOURCE_DATA=/home/denis/Documents/DIP7/Client/map/proj-9.2.0/data" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;188;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;0;")
add_test(test_tinshift "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/test_tinshift")
set_tests_properties(test_tinshift PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests;PROJ_SOURCE_DATA=/home/denis/Documents/DIP7/Client/map/proj-9.2.0/data" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;198;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;0;")
add_test(test_misc "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/test_misc")
set_tests_properties(test_misc PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests;PROJ_SOURCE_DATA=/home/denis/Documents/DIP7/Client/map/proj-9.2.0/data" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;208;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;0;")
add_test(test_fork "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/test_fork")
set_tests_properties(test_fork PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests;PROJ_SOURCE_DATA=/home/denis/Documents/DIP7/Client/map/proj-9.2.0/data" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;219;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/unit/CMakeLists.txt;0;")
subdirs("../../googletest-build")
