# CMake generated Testfile for 
# Source directory: /home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli
# Build directory: /home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/test/cli
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test27 "bash" "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/test27" "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/proj")
set_tests_properties(test27 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests" WORKING_DIRECTORY "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/test/cli" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/cmake/ProjTest.cmake;16;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;10;proj_add_test_script_sh;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;0;")
add_test(test83 "bash" "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/test83" "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/proj")
set_tests_properties(test83 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests" WORKING_DIRECTORY "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/test/cli" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/cmake/ProjTest.cmake;16;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;11;proj_add_test_script_sh;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;0;")
add_test(testproj "bash" "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/testproj" "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/proj")
set_tests_properties(testproj PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests" WORKING_DIRECTORY "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/test/cli" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/cmake/ProjTest.cmake;16;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;12;proj_add_test_script_sh;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;0;")
add_test(testinvproj "bash" "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/testinvproj" "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/invproj")
set_tests_properties(testinvproj PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests" WORKING_DIRECTORY "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/test/cli" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/cmake/ProjTest.cmake;16;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;13;proj_add_test_script_sh;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;0;")
add_test(testvarious "bash" "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/testvarious" "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/cs2cs")
set_tests_properties(testvarious PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests" WORKING_DIRECTORY "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/test/cli" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/cmake/ProjTest.cmake;16;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;14;proj_add_test_script_sh;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;0;")
add_test(testdatumfile "bash" "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/testdatumfile" "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/cs2cs")
set_tests_properties(testdatumfile PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests" WORKING_DIRECTORY "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/test/cli" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/cmake/ProjTest.cmake;16;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;15;proj_add_test_script_sh;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;0;")
add_test(testIGNF "bash" "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/testIGNF" "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/cs2cs")
set_tests_properties(testIGNF PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests" WORKING_DIRECTORY "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/test/cli" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/cmake/ProjTest.cmake;16;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;16;proj_add_test_script_sh;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;0;")
add_test(testntv2 "bash" "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/testntv2" "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/cs2cs")
set_tests_properties(testntv2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests" WORKING_DIRECTORY "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/test/cli" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/cmake/ProjTest.cmake;16;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;17;proj_add_test_script_sh;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;0;")
add_test(testprojinfo "bash" "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/testprojinfo" "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/projinfo")
set_tests_properties(testprojinfo PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests" WORKING_DIRECTORY "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/test/cli" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/cmake/ProjTest.cmake;16;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;18;proj_add_test_script_sh;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;0;")
add_test(testcct "bash" "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/testcct" "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/bin/cct")
set_tests_properties(testcct PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/data/for_tests" WORKING_DIRECTORY "/home/denis/Documents/DIP7/Client/map/build-proj-9.2.0-Desktop_Qt_5_14_2_GCC_64bit-Debug/test/cli" _BACKTRACE_TRIPLES "/home/denis/Documents/DIP7/Client/map/proj-9.2.0/cmake/ProjTest.cmake;16;add_test;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;19;proj_add_test_script_sh;/home/denis/Documents/DIP7/Client/map/proj-9.2.0/test/cli/CMakeLists.txt;0;")
